logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
docs:
  git_repository: "https://github.com/langchain-ai/langchain-api-docs-html.git"
  local_directory: "../../data/langchain-api-docs"
vector_store:
  index_name: "langchain-doc-index"
  embedding_model: "text-embedding-3-small"
  ingestion:
    chunk_size: 600
    chunk_overlap: 50
llm:
  chat_model_name: "gpt-4o"
  summarization_model_name: "gpt-3.5-turbo"