logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
vector_store:
  index_name: "langchain-doc-index"
  embedding_model: "text-embedding-3-small"
  ingestion:
    path_to_documents: "C:\\Workspace\\GitHub-Projects\\LangChainDocumentationHelper\\data\\langchain-docs\\api.python.langchain.com\\en\\latest"
    chunk_size: 600
    chunk_overlap: 50
llm:
  chat_model_name: "gpt-4o"
  summarization_model_name: "gpt-3.5-turbo"